---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: meshrr-core
spec:
  clusterIP: None
  ports:
  - name: bgp
    port: 179
    protocol: TCP
    targetPort: bgp
  selector:
    app: meshrr-evpnrs
  type: ClusterIP
# ---
# apiVersion: metallb.io/v1beta1
# kind: IPAddressPool
# metadata:
#   name: routeserver-mgt
#   namespace: metallb
# spec:
#   addresses:
#   - 192.168.18.0/24
#   autoAssign: false
# ---
# apiVersion: metallb.io/v1beta1
# kind: L2Advertisement
# metadata:
#   name: routeserver-mgt
#   namespace: metallb
# spec:
#   ipAddressPools:
#   - routeserver-mgt
#   interfaces:
#   - ens3
